iosevka16: &iosevka16 Iosevka Custom:pixelsize=16

bg: &bg 000000ff
bg2: &bg2 181818ff
fg: &fg 888888ff
green: &green 22aa22ff
red: &red aa2222ff
yellow: &yellow 888800ff
poll: &poll 2000

bar:
  location: bottom
  height: &height 24
  spacing: &spacing 8

  foreground: *fg
  background: *bg

  font: *iosevka16

  center:
    - clock:
        time-format: "%R %a %d/%m"
        content:
          - string:
              text: "{time}"

  left:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: *yellow}
                - string: {text: ": {title}", max: 70}

  right:
    - cpu:
        anchors:
          bar: &bar
            margin: 2
            text: ""
        poll-interval: *poll
        content:
          map:
            conditions:
              id >= 0:
                - ramp:
                    tag: cpu
                    items:
                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: *bg
                                  size: 0

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 002f44ff
                                  size: 1

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 104055ff
                                  size: 2

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 205c65ff
                                  size: 3

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 307876ff
                                  size: 4

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 419587ff
                                  size: 5

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 53b298ff
                                  size: 6

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 6ab59bff
                                  size: 7

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 88c087ff
                                  size: 8

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: a4cc77ff
                                  size: 9

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: bfd867ff
                                  size: 10

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: d0d360ff
                                  size: 11

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: e0c855ff
                                  size: 12

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: e8b94bff
                                  size: 13

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: e2923eff
                                  size: 14

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: dc6b32ff
                                  size: 15

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: d54526ff
                                  size: 16

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: cd1e1aff
                                  size: 17

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: bb1817ff
                                  size: 18

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: ff3a32ff
                                  size: 19

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: ff1f26ff
                                  size: 20

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: ff0b1aff
                                  size: 21

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: e8001cff
                                  size: 22

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: c4001eff
                                  size: 23

                      - string:
                          <<: *bar
                          deco:
                            stack:
                              - background: {color: *bg2}
                              - underline:
                                  color: 9f0020ff
                                  size: 24

    - script:
        path: ~/.config/yambar/temperature.sh
        args: [*poll]
        anchors:
          cool: &cool 2fb7c4ff
          warm: &warm e0c555ff
          hot: &hot e3493fff
          text: &text "{temperature:.0}°C"
        content:
          map:
            conditions:
              temperature < 40:
                - string:
                    text: *text
                    foreground: *cool
              temperature < 50:
                - string:
                    text: *text
              temperature < 70:
                - string:
                    text: *text
                    foreground: *warm
              temperature >= 70:
                - string:
                    text: *text
                    foreground: *hot


    - mem:
        poll-interval: *poll
        content:
          - string: {text: "RAM ", foreground: *yellow}
          - string: {text: "{used:mib:5}"}

    - network:
        poll-interval: *poll
        content:
          map:
            default:
              empty: {}
            conditions:
              name == wlp98s0:
                - string: {text: "WIFI ", foreground: *yellow}
                - map:
                    default:
                      string: {text: "{ssid}"}
                    conditions:
                      state == down:
                        string: {text: "<off>"}

    - battery:
        name: BAT1
        poll-interval: *poll
        smoothing-secs: 100
        content:
          - string: {text: "BAT ", foreground: *yellow}
          - map:
              conditions:
                estimate != "99:00" && estimate != "00:00":
                  - string: {text: "{estimate} "}
          - map:
              default:
                string: {text: "o"}
              conditions:
                state == charging && estimate != "99:00":
                  string: {text: "+", foreground: *green}
                state == discharging:
                  string: {text: "-", foreground: *red}
          - map:
              default:
                string: {text: "{capacity}"}
              conditions:
                capacity <= 30 && state == discharging:
                  string: {text: "{capacity}", foreground: *red}
