[buildPlans.IosevkaSimple]
family = "Iosevka Simple"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaSimple.variants.design]
one = "base-flat-top-serif"
two = "straight-neck-serifless"
three = "two-arcs"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "straight-bar"
seven = "straight-serifless"
eight = "crossing"
zero = "dotted"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-g = "toothless-rounded-serifless-capped"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-q = "straight"
capital-v = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "serifed"
j = "serifed"
k = "straight-serifless"
l = "serifed-semi-tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "flat-hook-short-neck"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "rounded-vertical-sides-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
punctuation-dot = "round"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "threefold"
dollar = "through"
bar = "natural-slope"
question = "smooth"

[buildPlans.IosevkaSimple.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaSimple.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaSimple.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaSimple.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaSimple.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
