#!/bin/sh

CONFIG="$HOME/.config/river"

# See the river(1), riverctl(1), and filtile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# spawn applications
riverctl map normal Super Return spawn $TERMINAL
riverctl map normal Super S spawn fuzzel
riverctl map normal Super V spawn "cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"

# quit focused window
riverctl map normal Super Q close

# exit river
riverctl map normal Super+Shift+Control Q exit

# focus views
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap views
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# focus output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# send view to output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# set focused view to main view
riverctl map normal Super Z zoom

# change main ratio
riverctl map normal Super H send-layout-cmd filtile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd filtile "main-ratio +0.05"

# change main count
riverctl map normal Super+Shift H send-layout-cmd filtile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd filtile "main-count -1"

# move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# snap views to edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# resize floating windows
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical -100
riverctl map normal Super+Alt+Shift K resize vertical 100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# move/resize with mouse
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# tags manipulation
for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# all tags manipulation
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# layout manipulation
riverctl map normal Super F toggle-float
riverctl map normal Super M send-layout-cmd filtile "monocle"
riverctl map normal Super+Shift F toggle-fullscreen

# layout orientation
riverctl map normal Super Up    send-layout-cmd filtile "main-location top"
riverctl map normal Super Right send-layout-cmd filtile "main-location right"
riverctl map normal Super Down  send-layout-cmd filtile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd filtile "main-location left"

# passthrough mode
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# volume
RAISE_VOLUME="amixer sset Master 5%+"
LOWER_VOLUME="amixer sset Master 5%-"
SET_MUTE="amixer sset Master toggle"
riverctl map normal None XF86AudioRaiseVolume spawn "$RAISE_VOLUME"
riverctl map normal None XF86AudioLowerVolume spawn "$LOWER_VOLUME"
riverctl map normal None XF86AudioMute spawn "$SET_MUTE"
riverctl map normal Super F2 spawn "$RAISE_VOLUME"
riverctl map normal Super F1 spawn "$LOWER_VOLUME"

# media
MEDIA_TOGGLE="playerctl play-pause"
MEDIA_PREV="playerctl previous"
MEDIA_NEXT="playerctl next"
riverctl map normal None XF86AudioMedia spawn "$MEDIA_TOGGLE"
riverctl map normal None XF86AudioPlay  spawn "$MEDIA_TOGGLE"
riverctl map normal None XF86AudioPrev  spawn "$MEDIA_PREV"
riverctl map normal None XF86AudioNext  spawn "$MEDIA_NEXT"
riverctl map normal Alt F1 spawn "$MEDIA_TOGGLE"
riverctl map normal Alt F2 spawn "$MEDIA_PREV"
riverctl map normal Alt F3 spawn "$MEDIA_NEXT"

# brightness
BRI_RAISE="brightnessctl set 2%+"
BRI_LOWER="brightnessctl set 2%-"
riverctl map normal None XF86MonBrightnessUp   spawn "$BRI_RAISE"
riverctl map normal None XF86MonBrightnessDown spawn "$BRI_LOWER"
riverctl map normal Super F4 spawn "$BRI_RAISE"
riverctl map normal Super F3 spawn "$BRI_LOWER"

# screenshot
riverctl map normal None Print spawn "$CONFIG/screenshot/selection.sh"
riverctl map normal Shift Print spawn "$CONFIG/screenshot/full.sh"

# cursor behavior
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

# colors
riverctl background-color 0x181818
riverctl border-color-focused 0x696355
riverctl border-color-unfocused 0x181818
riverctl border-width 3

# rules
riverctl rule-add -app-id 'osu!' tearing
riverctl rule-add -app-id 'vesktop' tags $((1 << 2))
riverctl rule-add -app-id 'zoom' tags $((1 << 3))
riverctl rule-add -app-id "*" ssd
riverctl rule-add -app-id "bar" csd

# window layout manager
riverctl default-layout filtile

# keyboard layout config
riverctl keyboard-layout -options grp:switch,grp:win_space_toggle,grp_led:scroll us,il

# keyboard repeat rate
riverctl set-repeat 25 600

# mouse/pointer config
riverctl input "pointer*" accel-profile flat
riverctl input "*Mouse" pointer-accel -0.4

# touchpad config
touchpad="*Touchpad"
riverctl input $touchpad events enabled
riverctl input $touchpad click-method clickfinger
riverctl input $touchpad drag enabled
riverctl input $touchpad disable-while-typing enabled
riverctl input $touchpad natural-scroll enabled
riverctl input $touchpad tap enabled
riverctl input $touchpad tap-button-map left-right-middle

# tablet config
tablet="tablet*"
riverctl input $tablet map-to-output HDMI-A-1

# manually configure monitors
riverctl map normal Super+Shift D spawn "wlr-randr --output eDP-1 --toggle"

export WAYLAND_DISPLAY=wayland-1
export XDG_CURRENT_DESKTOP=river

# autostart
MONITOR_CONFIG="$CONFIG/config-monitor-wayland.sh"
riverctl spawn "$MONITOR_CONFIG"
riverctl spawn "filtile -view-padding 0 -outer-padding 0"
riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl spawn waybar

exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
